### ISSUE TITLE
Dropdown is closed when the user selects the very last item

### ISSUE THREAD

**Issue by yrudyy** [stratos-vetsos/react-selectrix#11]
Even though I've set stayOpen to true, the dropdown keeps closing when I click the last item.
The bug is reproducible at React Selectrix Demo page too (https://stratos-vetsos.github.io/react-selectrix/)

**Comment by stratos-vetsos** [comment]
Hi yruddy,

That's how it is indented to be.
The stayOpen helps the user to select all the items, but when no other item is there to select, there is no reason for the component to be open.

Do you disagree?

**Comment by yrudyy** [comment]
@stratos-vetsos: Maybe I described it in a wrong way. Just go to https://stratos-vetsos.github.io/react-selectrix/, set any dropdown's stayOpen to true, open the dropdown and then scroll down to the very last item. If you click on it, the dropdown is closed immediately although there are still options left in the list.

**Comment by stratos-vetsos** [comment]
This should be fixed now ( v.1.0.14 ) !
Let me know if any issues,

Best Regards
