### ISSUE TITLE
Search is showing matches from the whole option item, not title

### ISSUE THREAD

**Issue by yrudyy** [stratos-vetsos/react-selectrix#14]
**Steps to reproduce:**
1. Go to https://stratos-vetsos.github.io/react-selectrix/
2. Scroll down to Ajax Example.
3. Type **1** in the search field.

**Expected result:**
Only options that contain search key in the title should be shown

**Actual result:**
Multiple options are shown - probably these items contain **1** in some fields but that is misleading for the user.
<img width="372" alt="options" src="https://user-images.githubusercontent.com/898656/43205345-d62bb7e6-902b-11e8-9eb7-8e784f8e9d9d.PNG">

**Comment by stratos-vetsos** [comment]
@casufi gj
